name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Show repo top-level (debug)
        run: ls -la

      - name: Build with Gradle (assembleDebug)
        # run with --info so logs show outputs
        run: ./gradlew assembleDebug --info
        # if your module name is not 'app', replace assembleDebug with :<module>:assembleDebug

      - name: List build outputs (debug)
        run: |
          echo "Listing app/build/outputs:"
          ls -la app/build/outputs || true
          echo "Listing all APKs under repo:"
          find . -type f -name "*.apk" -maxdepth 6 -print || true

      - name: Upload any built APKs
        uses: actions/upload-artifact@v4
        with:
          name: cattle-breed-apk
          path: |
            app/build/outputs/**/*.apk
            **/build/outputs/**/*.apk
            app/build/outputs/apk/**/*.apk
            */build/outputs/apk/**/*.apk
